### ISSUE TITLE
Log to SDcard

### ISSUE THREAD

**Issue by jetpax** [esp32m/core#12]
You have implemented a nice logging system. Do you have any plans to support logging to SDcard? The use case would be for devices with intermittent or expensive web access such as mobile.

**Comment by dyarkovoy** [comment]
Hi, logging to SD card is supported. You just need to mount your SD card as explained here: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/fatfs.html?highlight=sd#using-fatfs-with-vfs-and-sd-cards
and then use VFS appender (esp32m/log/vfs.hpp)

**Comment by jetpax** [comment]
> Hi, logging to SD card is supported. You just need to mount your SD card as explained here: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/fatfs.html?highlight=sd#using-fatfs-with-vfs-and-sd-cards
> 
> and then use VFS appender (esp32m/log/vfs.hpp)

Is this for onchip flash or SDcard?
How would i setup an SDcard hw(eg pins) or use a more robust fs eg littlefs?

**Comment by dyarkovoy** [comment]
It is for both.
Depending on how your card is connected, you can use `esp_vfs_fat_sdspi_mount()` or `esp_vfs_fat_sdmmc_mount()` to setup SD card hw (pins and other details), documented here: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/fatfs.html?highlight=sd#_CPPv423esp_vfs_fat_sdspi_mountPKcPK12sdmmc_host_tPK21sdspi_device_config_tPK26esp_vfs_fat_mount_config_tPP12sdmmc_card_t
and here: 
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/fatfs.html?highlight=sd#_CPPv423esp_vfs_fat_sdmmc_mountPKcPK12sdmmc_host_tPKvPK26esp_vfs_fat_mount_config_tPP12sdmmc_card_t
The examples are here: 
https://github.com/espressif/esp-idf/tree/ab03c2ea13ecaac1510b75e93b32cf0c472640fb/examples/storage/sd_card

The examples should only be used to mount your SD card to the virtual file system. Once mounted, you should use esp32m/log/vfs.hpp to enable logging to file on your SD card

**Comment by jetpax** [comment]
That's great thank you!
