### ISSUE TITLE
RMT LED string bus support

### ISSUE THREAD

**Issue by jetpax** [esp32m/core#14]
I've added RMT led support  to my fork, but it is a naive implementation that uses the espressif __led_strip managed component directly  because I dont need one-wire in my application , though ideally it would sit on top of your RMT IO abstraction.

 I was wondering if you had any plans to support addressable LED strips  going forward for example as a 'bus' ?

**Comment by dyarkovoy** [comment]
No plans to add support for LED strips at the moment, but you're welcome to submit PR with your implementation. 
It is better to add espressif/led_strip dependency in idf_component.yml, rather than in CMakeLists.txt

**Comment by jetpax** [comment]
OK thanks, I submitted a PR
