### ISSUE TITLE
DebugPins documentation error

### ISSUE THREAD

**Issue by jetpax** [esp32m/core#18]
Device UI fails to render using [DebugPins](https://esp32m.com/docs/reference/components/) with 

<img width="764" alt="image" src="https://github.com/esp32m/core/assets/6566148/ccc9998d-8b44-4805-bd8f-0de9ea233a4e">

should read 

<img width="756" alt="image" src="https://github.com/esp32m/core/assets/6566148/70e27159-7646-43df-97a2-170591ae9801">

**Comment by dyarkovoy** [comment]
Corrected, thank you
