### ISSUE TITLE
decouple UI

### ISSUE THREAD

**Issue by jschoch** [esp32m/core#2]
This project looks great, thanks for sharing it!!!

I wonder if you have considered making the UI and react decoupled from the other components and just serving a compiled SPA via a CDN or cloud storage (s3 or something)?  It would save all the space and make development of the UI not require flashing assuming the API didn't change.

**Comment by dyarkovoy** [comment]
Thank you for the kind words. It is very easy to decouple the UI. 

Assuming you know the IP of your ESP32, go to web-ui/webpack.config.js and replace the last line with
`
module.exports=builder(__dirname, {
 devhost:"IP_ADDRESS_OF_YOUR_ESP32",
});
`
After that, run `yarn start` in the web-ui folder to start local server for the UI. You can now open http://localhost:9000 in your web browser and make changes to the UI sources, the changes should be applied automatically.
This will still bundle the UI with the code though. If you want to completely strip the UI from the firmware binary, then in your project folder:
1. remove "web-ui" from  EXTRA_COMPONENT_DIRS in CMakeLists.txt
2. remove web-ui from  PRIV_REQUIRES in main/CMakeLists.txt
3. in main/main.cpp, remove `#include <ui.hpp>` and replace `initUi(new Ui(new ui::Httpd()));` with `new Ui(new ui::Httpd());`
4. if you use `esp32m.py` script to build the firmware, add `--ui=skip` command line option: `python path-to-esp32m.py build --ui=skip`

This will remove compiled javascript and HTML files from the firmware, but will keep the Websocket server on the chip, allowing you to connect remotely with the IP address as explained above.
Finally, if you don't want the UI at all, not even via remote connection, remove the line  `initUi(new Ui(new ui::Httpd()));` from the main/main.cpp completely.

**Comment by jschoch** [comment]
Thanks, this is handy advice!!!  Happy to close or you may want to add it to your docs.

**Comment by dyarkovoy** [comment]
Yes I definitely need to add this to the docs, and I will when time permits. Let the issue remain open until I do so, as a reminder for me.

**Comment by dyarkovoy** [comment]
Added to docs: https://esp32m.com/docs/reference/ui
