### ISSUE TITLE
Webserver Password protection

### ISSUE THREAD

**Issue by berni2288** [esp32m/core#23]
Hello there,

thanks for the awesome project!

I wonder if there is a way to protect the Webserver with Basic auth? Exposing it without is quite dangerous. Or is there at least some way to intercept the HTTP requests and implement it yourself?
Thanks!

**Comment by dyarkovoy** [comment]
Hello, it is not exposed to the outside world, your WiFi router takes care
of that. You will not be able to access the device with esp32m from the
outside, unless you configure port forwarding on your router. It is exposed
only within your local/home network. Or do you need authentication within
your LAN?

вт, 22 жовт. 2024 р., 22:58 користувач Bernhard Kaszt <
***@***.***> пише:

**Comment by berni2288** [comment]
I need authentication within my LAN. Router-NAT is not a proper protection for anything.
Any device in the same LAN can access the ESP32, for example any web page that I open in my browser would be able to make HTTP requests to the ESP32. So relying on NAT as your security is really obscurity and not secure.
Also there are more people than just me who are connected to the same Wifi :)

I have hundreds of devices connected to my Wifi, but not a single one has no password protection.

**Comment by dyarkovoy** [comment]
Ok, I get it.
No problem, I can add basic auth to the HTTP server.
Are you okay with configuring the username/password at build time in
sdkconfig?

ср, 23 жовт. 2024 р. о 16:22 Bernhard Kaszt ***@***.***> пише:

**Comment by berni2288** [comment]
Yeah anything would be better than the current situation :) Thanks!

**Comment by dyarkovoy** [comment]
Added, please check the latest commit.
Use the following defines in `sdkconfig.defaults`:
```
CONFIG_ESP32M_UI_HTTPD_BASIC_AUTH=y
CONFIG_ESP32M_UI_HTTPD_BASIC_AUTH_USERNAME="admin"
CONFIG_ESP32M_UI_HTTPD_BASIC_AUTH_PASSWORD="pass"
```

**Comment by berni2288** [comment]
works, thanks :heart:
