### ISSUE TITLE
Understanding what your project can/cannot do

### ISSUE THREAD

**Issue by dpetican** [esp32m/core#3]
First, having looked through the documentation I would say you have done a tremendous job.  Quite amazing.  However, I don't see any documentation on how to extend the functionality beyond what you have already coded.  I haven't yet dived into the actual source code which of course I need to do.  I'm not that familiar with the IDF framework as I should be having done most, if not all of my ESP work in Arduino.

Without looking at the source code though I can imagine how one could tweak the UI.  It just occurred to me that since the UI can be carved out of the source code and run elsewhere would it be possible to build a native react app?

I've been working on a system for over 4 years for my client that runs a water purification system.  The latest hardware iteration uses an ESP32.  The overall architecture is a microcontroller running a state machine that interfaces to the pumps, valves, and sensors to run the machine.  The ESP32 is only there to facilitate to using a custom Android application to configure the system, firmware updating, downloading application logfiles from the SD card etc.  For my particular use case though what I want to discover is how I would:

1.  Add an RTC so that I could timestamp outgoing messages (log, socket, SD card)
2.  Write my application (not system log) messages to an SD card.  Then download in binary over sockets.
3.  Create (as I have done already) a socket to UART bridge to talk to the microntroller that is running the machine.  Maybe MQTT as well.
4. Does esp32m function in host+AP mode?  So that I could just connect to it from an Android phone or something like Postman on my laptop to send/receive socket messages?  In any event we would want to use this to connect to the ESP32 without a router present like we do now.  That is walk up to the machine and and connect to the access point on the ESP32 then launch our custom app.
5. Upload files in binary over sockets to be used to flash the machine's microntroller.

Lastly, are you available for consulting work?  I'm thinking the above is not too difficult to do, but I still have my hands full on the next version of the state machine that runs my client's machine.  After I learn more I would definitely approach them with a proposal as I feel what you have already done as open source will save them a lot of development time.  Thank you.

**Comment by dyarkovoy** [comment]
I appreciate the kind words and let me try to address your questions.

- **Extending the functionality.** The code is modular, and I believe, the source would be the best documentation in this case. For example, if you need to add new device, check `core/esp32m/src/dev` (source) and `core/esp32m/include/esp32m/dev` (headers) folders. Every cpp/hpp pair describes a device, may be used as a template to create drivers for new devices.
-  **Building a native react app.** It is certainly possible. The core communicates with the UI with the very simple Websockets/JSON based request/response protocol, so it is possible to build any kind of UI that would connect to your esp32-based device via host name or IP using Websockets
- **Adding an RTC to timestamp outgoing messages.** The `esp32m` can automatically sync with NTP time server once connected to Internet (see `net::useSntp();` in examples/olimex-eth/main/main.cpp), from there it's just a matter of using standar C/C++ functions to get current time, such as `gettimeofday()` etc.
- **Writing messages to SD card.** Right now there's no direct support for SD cards, but I will see how to add it, I don't think that would be a problem. 
- **Then download in binary over sockets.** - Certainly possible using standard C sockets. If you already have Arduino code for that in place, you could probably just copy it as is, unless it uses some 3rd party Arduino libs
- **Create (as I have done already) a socket to UART bridge** - same thing, porting existing C code should not be a problem. 
- **Maybe MQTT as well.** MQTT client is built in, and a descendant of `esp32m::Device` class can override `pollSensors()` , and sensor data will be automatically routed via MQTT. You can search for `pollSensors` in .cpp files under  `core/esp32m/src/dev` for examples of how that is done.
- **Does esp32m function in host+AP mode?** When esp32m starts, first if checks whether any APs were hard coded, or saved in the config, in which case it starts WiFi in STA mode and tries to connect to configured AP(s). If there are no configured APs, or if connection failed, it switches to STA+AP mode and waits for someone to connect and configure AP to connect to.
- **Using esp32m in AP mode as described in your no.4** That is certainly possible simply by not configuring any APs in your code, the esp32m will autostart AP and its HTTP/WS server will be available on 192.168.4.1:80 (easily configurable as well)
- **Upload files in binary over sockets.** Certainly possible by migrating your existing C code.
- **Availability for consulting.** Sure, feel free to ask, I would be happy to help.

**Comment by dyarkovoy** [comment]
I just checked ESP-IDF docs, and SD card functionality is natively supported and is well-documented here: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/fatfs.html?highlight=sd

**Comment by dpetican** [comment]
Thanks for your interest.  Obviously I need to do a dive into the source code and get up-to-date on the IDF.  Probably bootstrap your code onto a bare ESP32 and see what I can get it to do.  For now I will mention though that the point of the RTC is to timestamp the  application messages going to the SD card because the entire system will not always have internet connectivity.  In some cases its not even possible.  For example remote farms.  Dairy cows love low TDS water.  In which case the log files are downloaded manually at service intervals.

**Comment by dyarkovoy** [comment]
I see, so your ESP32 devices must be powered on all the time, plus you need UI to set the time manually, in case the chip is powered down at some point. Once the time is set, the RTC will work by default and functions like `gettimeofday()` will return correct time for your timestamping needs, until the next power down
