### ISSUE TITLE
Can't change IP address for ethernet device / olimex-eth

### ISSUE THREAD

**Issue by MrPec** [esp32m/core#8]
When I change the IP address of a T-Internet-POE Lilygo device (uses same HW as Olimex) the device listens on that IP - good!
However, on restart it's back to DHCP, and I can't open up the http://.../netifs page anymore.

On the log, it just displays:
0:00:00:03.003 I eth  my IP: 192.168.1.63
0:00:20:24.628 D ui-http-53  session opened
0:00:22:41.084 I netifs  1 configured, 1 active
0:00:22:42.293 I netifs  1 configured, 1 active
0:00:22:43.514 I netifs  1 configured, 1 active
0:00:22:44.723 I netifs  1 configured, 1 active
...

Plus, W-LAN just displays "Available access points" forever.
Only way to reset and get the config page is to clear the flash.

Any ideas?

Thanks!

**Comment by dyarkovoy** [comment]
Sorry for the late response, I somehow missed E-mail notification for this issue. 
You're right, there was a problem with ethernet interface configuration, please see if it works for your now.
W-LAN page was not loading properly because WiFi module was not being used in main.cpp, fixed that too.
